### ISSUE TITLE
Support for PHP7?

### ISSUE THREAD

**Issue by razvanphp** [blackfireio/php-sdk#1]
As the new version is really close this year (RC6 now) I tried it on my dev machine. Unfortunately, the performance is not so great, so I wanted to know what slows it down.

When I try to install the blackfire-probe, php5-cli, json and readline gets automatically installed, and I guess the extension is compiled for 20131226.

Any thoughts on PHP7 support?

Thank you!

**Comment by fabpot** [comment]
We are working on PHP7 support, but it's not ready yet.
