### ISSUE TITLE
Fatal errors in LoopClient

### ISSUE THREAD

**Issue by clslrns** [blackfireio/php-sdk#16]
Hi, guys.

This classes do not exist anymore:
* `Blackfire\Exception\LogicException`
* `Blackfire\Exception\RuntimeException`

But they are used in LoopClient: https://github.com/blackfireio/php-sdk/blob/master/src/Blackfire/LoopClient.php#L15.

It causes PHP errors like that: 

    PHP Fatal error:  Class 'Blackfire\Exception\LogicException' not found in .../vendor/blackfire/php-sdk/src/Blackfire/LoopClient.php on line 114

**Comment by romainneutron** [comment]
Fixed as of https://github.com/blackfireio/php-sdk/commit/8e75d2f6e1f1817d745c0068e8cf54c385e485ce

Thanks for reporting!

**Comment by romainneutron** [comment]
Released as of https://github.com/blackfireio/php-sdk/releases/tag/v1.5.17
