### ISSUE TITLE
PHP 5.3 compatibility

### ISSUE THREAD

**Issue by echernyavskiy** [blackfireio/php-sdk#20]
PHP Code Sniffer check with the [PHPCompatibility](https://github.com/wimg/PHPCompatibility) standard reports the following PHP 5.3 compatibility issues:

    FILE: .../vendor/blackfire/php-sdk/src/Blackfire/Bridge/Guzzle/Middleware.php
    ------------------------------------------------------------------------------------------------------------------------
    FOUND 4 ERRORS AFFECTING 3 LINES
    ------------------------------------------------------------------------------------------------------------------------
    34 | ERROR | 'callable' type declaration is not present in PHP version 5.3 or earlier
    |       | (PHPCompatibility.PHP.NewScalarTypeDeclarations)
    34 | ERROR | "callable" keyword is not present in PHP version 5.3 or earlier (PHPCompatibility.PHP.NewKeywords.Found)
    44 | ERROR | "callable" keyword is not present in PHP version 5.3 or earlier (PHPCompatibility.PHP.NewKeywords.Found)
    120 | ERROR | Function array dereferencing is not present in PHP version 5.3 or earlier
         |       | (PHPCompatibility.PHP.NewFunctionArrayDereferencing)

Would the maintainers be interested in a patch that removes **callable** type-hints and untangles function array dereferencing?

**Comment by romainneutron** [comment]
Guzzle middleware is only compatible with Guzzle 6, supporting only PHP 5.5. No problem with this code
