### ISSUE TITLE
Support for PHPUnit 6

### ISSUE THREAD

**Issue by HEKET313** [blackfireio/php-sdk#31]
When I do assertion, I get an error

>  'PHPUnit_Framework_Constraint' not found in .../vendor/blackfire/php-sdk/src/Blackfire/Bridge/PhpUnit/TestConstraint.php on line 16

And that's ok because in PHPUnit 6.5 this is class `\PHPUnit\Framework\Constraint\Constraint`

How can I use your SDK with latest PHPUnit version?

**Comment by romainneutron** [comment]
Hello,

PHPUnit 6 support has been released in latest versions
