### ISSUE TITLE
Is it possible to collect all the profiles ?

### ISSUE THREAD

**Issue by maidmaid** [blackfireio/php-sdk#36]
Could be useful to log all the profiles/costs thanks to a logger for analysing them trough the Time (with an ELK or similar). 

```php
$blackfire = new \Blackfire\Client($config, $logger);
```

**Comment by romainneutron** [comment]
Hello @maidmaid 
Not sure to understand your question. What do you mean by "collect all the profiles" ?
Are you proposing to profile your request regularly and send the results to a timeseries DB like graphite?

**Comment by maidmaid** [comment]
Hello @romainneutron.

> Are you proposing to profile your request regularly and send the results to a timeseries DB like graphite?

Yes, it's my point.

**Comment by romainneutron** [comment]
Hello,

Collecting lots of profiles adds an large overhead and does not bring that much value if the data is not used.
If you want to collect envelope costs, it's quite easy to do
