### ISSUE TITLE
Warning: Ambiguous class resolution since v1.17.3

### ISSUE THREAD

**Issue by perice** [blackfireio/php-sdk#38]
Hello,

I get this warning:

Warning: Ambiguous class resolution, "Blackfire\Bridge\PhpUnit\TestConstraint" was found in both "/var/www/vendor/blackfire/php-sdk/src/Blackfire/Bridge/PhpUnit/TestConstraint71.php" and "/var/www/vendor/blackfire/php-sdk/src/Blackfire/Bridge/PhpUnit/TestConstraint5x.php", the first will be used.

when I run:

composer dump-autoload --optimize --no-dev --classmap-authoritative

**Comment by romainneutron** [comment]
Hello,
it's been fixed in https://github.com/blackfireio/php-sdk/releases/tag/v1.17.5

Thanks for reporting
