### ISSUE TITLE
Document integration with Swoole

### ISSUE THREAD

**Issue by sshymko** [blackfireio/php-sdk#40]
It would be great to add the [Swoole integration](https://github.com/upscalesoftware/swoole-blackfire) to https://blackfire.io/docs/integrations/index.

**Comment by lolautruche** [comment]
Hello @sshymko and sorry for this long delay (almost 2 years)...
It's been a long time since we added Swoole as a Blackfire integration: https://github.com/upscalesoftware/swoole-blackfire
