### ISSUE TITLE
PHP 5.3 compatibility

### ISSUE THREAD

**Issue by telemmaite** [blackfireio/php-sdk#41]
Guys you should **fix the PHP 5.3 compatibility** of the SDK.

https://blackfire.io/docs/reference-guide/php-sdk

> The Client works with PHP 5.3+.

https://github.com/blackfireio/php-sdk/blob/master/composer.json#L13
https://github.com/blackfireio/php-sdk/blob/master/src/Blackfire/Client.php#L117

Looks like nobody noticed since this commit which does only 50% of the job.
https://github.com/blackfireio/php-sdk/commit/dcc3c9ba0ca99d77cba0295ba3f9d4acd6be1c1d

It also misses here:
https://github.com/blackfireio/php-sdk/blob/dcc3c9ba0ca99d77cba0295ba3f9d4acd6be1c1d/src/Blackfire/Client.php#L125

**Comment by romainneutron** [comment]
Hello,
The SDK is compatible with PHP 5.3. Please point actual issues. If you experience a bug on PHP 5.3, please write a bug report.

Thanks,

**Comment by marcw** [comment]
Hi @telemmaite,

Thanks for reporting this issue. It is being fixed by #42. 

Please remember that this is an open-source project and that you can contribute to it. Also, please remember that issues written in a passive-aggressive always take a toll on maintainers.

**Comment by telemmaite** [comment]
I think you have missed one.
https://github.com/blackfireio/php-sdk/blob/master/src/Blackfire/Client.php#L145

```php
145:  public function closeScenario(Scenario $scenario, array $errors = [])
```

**Comment by romainneutron** [comment]
@telemmaite are you using the SDK with PHP 5.3?

**Comment by romainneutron** [comment]
> I think you have missed one.
> https://github.com/blackfireio/php-sdk/blob/master/src/Blackfire/Client.php#L145
> 
> ```
> 145:  public function closeScenario(Scenario $scenario, array $errors = [])
> ```

Fixed as of https://github.com/blackfireio/php-sdk/commit/27ac842a26a9babb955214385787a7c60430160d

**Comment by romainneutron** [comment]
Released as of https://github.com/blackfireio/php-sdk/releases/tag/v1.19.2

**Comment by telemmaite** [comment]
> @telemmaite are you using the SDK with PHP 5.3?

Yes we are, thank you for the quick fix.
