### ISSUE TITLE
This profile was generated with an outdated Blackfire Probe

### ISSUE THREAD

**Issue by mayro** [blackfireio/php-sdk#43]
Hello,
I use php-sdk to test my api (postman) with Blackfire, i followed the Blackfire doc, but i have empty result into my profiling and when i check via my blackfire profile i find an alert that i use an updated Blackfire Probe ...  can someone help me ? i used composer to install the PHP-sdk so i have the last version 1.19.1.
Thank you

**Comment by iamluc** [comment]
Did you install the Blackfire probe (PHP extension) as explained at https://blackfire.io/docs/up-and-running/installation ?

**Comment by romainneutron** [comment]
Please reopen if needed
