### ISSUE TITLE
No probe version detected. Fallback probe used?

### ISSUE THREAD

**Issue by binary-data** [blackfireio/php-sdk#57]
Everything was working fine until recently, and I didn't change any backfire settings or the code. Now I only get this:

![1](https://user-images.githubusercontent.com/875296/114688317-a2772480-9d25-11eb-96fe-aa91107425e1.png)
![2](https://user-images.githubusercontent.com/875296/114688340-a6a34200-9d25-11eb-8da6-93e30f89564c.png)

I am using the latest version of PHP SDK from Packagist, and I use it like this:

```php
<?php

use Blackfire\Client;
use Blackfire\ClientConfiguration;

$config = new ClientConfiguration('ID', 'TOKEN');

$blackfire = new Client($config);
$probe = $blackfire->createProbe();

register_shutdown_function(function () use ($blackfire, $probe) {
    $blackfire->endProbe($probe);
});

```

The data reaches blackfire.io since I can see new profiles. But it seems the data is somehow corrupted.

**Comment by iamluc** [comment]
Hi @binary-data ,
It means the `blackfire` PHP extension is not installed or loaded.
If you need help to fix that, please contact us at support@blackfire.io.
