### ISSUE TITLE
Commands monitoring doesn't work for Laravel

### ISSUE THREAD

**Issue by lkmadushan** [blackfireio/php-sdk#61]
```
Argument 1 passed to Blackfire\Bridge\Laravel\ObservableCommandProvider::Blackfire\Bridge\Laravel\{closure}() must be an instance of Illuminate\Console\Events\CommandStarting, instance of Illuminate\Console\Events\ScheduledTaskStarting given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 381 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Blackfire\\Bridge\\Laravel\\ObservableCommandProvider::Blackfire\\Bridge\\Laravel\\{closure}() must be an instance of Illuminate\\Console\\Events\\CommandStarting, instance of Illuminate\\Console\\Events\\ScheduledTaskStarting given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 381 at /var/www/html/vendor/blackfire/php-sdk/src/Blackfire/Bridge/Laravel/ObservableCommandProvider.php:36)
```

**Comment by dusandevic** [comment]
Applied fix doesn't work properly. It obviously helps to get rid of the mentioned error, but there is another one: 

`Undefined property: Illuminate\Console\Events\ScheduledTaskStarting::$input {"exception":"[object] (ErrorException(code: 0): Undefined property: Illuminate\\Console\\Events\\ScheduledTaskStarting::$input at /home/forge/xxxxxxxxxx/releases/123123123/vendor/blackfire/php-sdk/src/Blackfire/Bridge/Laravel/ObservableCommandProvider.php:37)`

**Comment by thomasdiluccio** [comment]
Hi @dusandevic. Thank you for raising this. I am exploring this so as to push a fix as soon as possible.

**Comment by thomasdiluccio** [comment]
@dusandevic The fix is in production: https://github.com/blackfireio/php-sdk/releases/tag/v1.27.1
