### ISSUE TITLE
[FATAL ERROR] The Laravel Octane bridge doesn't work (missing methods)

### ISSUE THREAD

**Issue by aran112000** [blackfireio/php-sdk#66]
Since first introduced in v1.30.0 the Laravel Octane bridge doesn't appear to have ever worked. There are references to `\BlackfireProbe::setAttribute()` throughout the code, yet this method isn't defined and I can't find traces of it in older versions either.

**Comment by aran112000** [comment]
@romainneutron - Would you mind reviewing and if happy merging this PR so we can deploy our fix?

**Comment by aran112000** [comment]
I'm not sure that's correct based on our tests.

The SDK in your documentation is said to be a replacement for the extension, for setups where it's not possible to use the extension. 

Even when we tested running in combination, it didn't resolve the issue, we still got the fatal error.

This patch resolved it in full when we deployed.

**Comment by romainneutron** [comment]
Hello @aran112000 
Thanks for reporting your issue.
We just released a new version of the SDK that fixes your issue https://github.com/blackfireio/php-sdk/releases/tag/v1.35.0

Please reopen an issue whenever you need
