### ISSUE TITLE
Blackfire and Xdebug clash

### ISSUE THREAD

**Issue by derickr** [blackfireio/php-sdk#69]
Hi,

in https://bugs.xdebug.org/view.php?id=2230 you see that there are issues with blackfire and Xdebug. I can't reproduce this. So perhaps you can? 

cheers,
Derick

**Comment by iamluc** [comment]
Hi @derickr,
Thanks for your report. I'll try to reproduce and let you know.

**Comment by derickr** [comment]
Cheers - feel free to find me on the foundation slack (I can invite you), or Room 11 (https://chat.stackoverflow.com/rooms/11/php) if you want to chat!

**Comment by derickr** [comment]
Does Blackfire use observers? And perhaps, removes it's own hook (like datadog trace did: https://github.com/DataDog/dd-trace-php/pull/2469 )

**Comment by iamluc** [comment]
Blackfire can use the observer API, but it's not the default, and seems disabled in the provided debug information.
And we don't remove the hooks.

**Comment by derickr** [comment]
Would you like to debug this together?

**Comment by iamluc** [comment]
Actually I think I found the culprit, and I opened a PR => https://github.com/xdebug/xdebug/pull/947

But sure, I'm available on Room 11 (or other platforms) if you want to discuss this!

**Comment by derickr** [comment]
I don't know your handle on R11, I'm @Derick (and there now) :-) Because I would like to be able to reproduce it locally first as well (so I can perhaps make a test).

**Comment by derickr** [comment]
Thanks for debugging and fixing this together! https://github.com/xdebug/xdebug/pull/948 was the final PR.
