### ISSUE TITLE
401:  while calling GET https://blackfire.io/api/v1/collab-tokens

### ISSUE THREAD

**Issue by apatuka** [blackfireio/php-sdk#72]
Hello, we just adquired the Blackfire Profiling & Monitoring service, we installed the PHP SDK for Version 5.6
This is my code inside my index.php

`			try {
				$config = new \Blackfire\ClientConfiguration("MY_CLIENT_ID", "MY_SERVER_TOKEN");
				$blackfire = new \Blackfire\Client($config);
				$probe = $blackfire->createProbe();	
			} catch(Exception $e) {
				echo $e->getMessage();
			}`
			
But i have this error
401:  while calling GET https://blackfire.io/api/v1/collab-tokens

**Comment by romainneutron** [comment]
Hello,
Please contact support@blackfire.io for getting support.
By the way, the client contfiguration  expects a client id and a client token. Blackfire has a concept of client id/token and server id/token, don't mix them.
