### ISSUE TITLE
[BUG] Undefined property: Blackfire\Bridge\Symfony\BlackfiredHttpClient::$defaultOptions

### ISSUE THREAD

**Issue by riki137** [blackfireio/php-sdk#73]
When calling ->withOptions() on BlackfiredHttpClient it crashes because it uses HttpClientTrait which requires $defaultOptions, but BlackfiredHttpClient does not have this property.

<img width="779" alt="image" src="https://github.com/blackfireio/php-sdk/assets/1223388/fb7c1367-6558-4326-8c2d-ab4894d8fb7a">

**Comment by romainneutron** [comment]
Hello,
It should be fixed as of https://github.com/blackfireio/php-sdk/releases/tag/v2.5.2

Thanks for reporting!
