### ISSUE TITLE
[BUG] BlackfiredHttpClient does not support 'base_uri' specified in underlying HttpClientInterface

### ISSUE THREAD

**Issue by riki137** [blackfireio/php-sdk#74]
It seems that BlackfiredHttpClient does not account for 'base_uri' being present only in the default options of the underlying client that it's decorating, since it passes static::OPTIONS_DEFAULTS as default options and tries to create URL from that. This makes profiling requests that rely on 'base_uri' in underlying client impossible.

Our base URI is specified in RetryableHttpClient.

![image](https://github.com/blackfireio/php-sdk/assets/1223388/5cd199b1-ba96-4535-812e-627fb3ac948d)

**Comment by romainneutron** [comment]
Hello,
It should be fixed as of https://github.com/blackfireio/php-sdk/releases/tag/v2.5.2

Thanks for reporting!
