### ISSUE TITLE
Messed up Configuration namespace

### ISSUE THREAD

**Issue by trylika** [blackfireio/php-sdk#8]
While initializing BlackFire Client, error is thrown:
 ```Argument 1 passed to Blackfire\Client::getRequestDetails() must be an instance of Blackfire\Configuration, instance of Blackfire\Profile\Configuration given, called in /var/www/vendor/blackfire/php-sdk/src/Blackfire/Client.php on line 266 and defined```

Problem is that `Configuration` Namespace changed, but somebody forgot to change definition in here:
https://github.com/blackfireio/php-sdk/blob/master/src/Blackfire/Client.php#L299

Applies to BlackFire SDK release 1.4.4

**Comment by romainneutron** [comment]
Fixed by https://github.com/blackfireio/php-sdk/commit/f05446f844669938e752f648e500e49916a06fc0
